### ISSUE TITLE
Version 0.4.1 breaks chai test for `fileupload` data attribute

### ISSUE THREAD

**Issue by mitnal** [tors/jquery-fileupload-rails#34]
I am not really sure if it is a problem of jquery-fileupload-rails but I have no other clue than that 0.4.1 fails my test and 0.4.0 passes. Perhaps somebody has a similar problem or can help me with this error.

```coffeescript
describe 'Fileupload', ->

  it 'initializes the fileuploader', ->
      $('#fileupload').fileupload()
      expect($('#fileupload')).to.have.data('fileupload')
```

This passes with 0.4.0 but fails with 0.4.1 with the following backtrace:
```
TypeError: Cannot read property 'ownerDocument' of null
    at Function.Sizzle.contains (http://localhost:3500/assets/jquery.js?body=1:4393:16)
    at Function.jQuery.extend.clone (http://localhost:3500/assets/jquery.js?body=1:6385:20)
    at HTMLDocument.<anonymous> (http://localhost:3500/assets/jquery.js?body=1:6034:18)
    at http://localhost:3500/assets/jquery.js?body=1:301:20
    at Function.jQuery.extend.map (http://localhost:3500/assets/jquery.js?body=1:774:13)
    at jQuery.fn.jQuery.map (http://localhost:3500/assets/jquery.js?body=1:300:33)
    at jQuery.fn.extend.clone (http://localhost:3500/assets/jquery.js?body=1:6033:15)
    at $.fn.inspect (http://localhost:3500/assets/chai-jquery.js?body=1:25:39)
    at formatValue (http://localhost:3500/assets/chai.js:3315:22)
    at formatProperty (http://localhost:3500/assets/chai.js:3487:19)
```

* jquery-fileupload-rails 0.4.1
* jquery_rails 2.2.1
* jquery 1.9.1
* chai-jquery-rails 1.1.1
* chai 1.4.2
* konacha 2.5.0

**Comment by felixbuenemann** [comment]
This issue is very old, please try 0.4.2.
